server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: dnjswns98!
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect



jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 86400000 # 24시간 